workflows:
  ios-workflow:
    name: Flangapp PRO iOS without publication
    max_build_duration: 30
    environment:
      vars:
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        APP_STORE_CONNECT_ISSUER_ID: 0f4b1570-ddfa-4aa9-b539-78a5df88ca47
        APP_STORE_CONNECT_KEY_IDENTIFIER: PGZF46PXCZ
        APP_STORE_CONNECT_PRIVATE_KEY: |-
         -----BEGIN PRIVATE KEY-----
         MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg/M2wl83jjV1hvNVg
         1zdehvV93qXE0F0UEYeFV8rrSK6gCgYIKoZIzj0DAQehRANCAAQkQFz518Kwhur9
         HxKg9hdX9FlhYzJoCs7ImXsRhc6o8YmyG6ZAxc82TujvW0bC6cEfJl0qcuJQ5ci6
         tJpZzIy+
         -----END PRIVATE KEY-----

        CERTIFICATE_PRIVATE_KEY: |-
         -----BEGIN RSA PRIVATE KEY-----
         MIIEpAIBAAKCAQEAkkvA5IcFcUvAVA2e5A6uOZ6fcvigKwid8vlMv5Tgorq/cDq0
         AsS8thC90L9fBPodw8MX9NKIlMp4hkSHDIXyRA1ZdJIwSS6IIfXUWtHqwQfqLi+d
         rOVIspqyyUJ2461KLHXvNEAYG32z78ipEJJm6t/M+8RZbYUC6vWn8CmrBC233mIj
         CH/GpR2j0+h6PMVI77lua+zulX48Znx/zXeQr4pRmY+Pfuq/OiwjspxDfi7jLBWd
         IvKq3OgZXg8dIq9+DMqt/G+zxjPnvUqxuMurEN6bmoWzM4/toSF7KoqnuMfFQ8L8
         tqO/qM1u5C3vREdb9/RsnhhaOPjLydP6SV6D9wIDAQABAoIBAA2hbZdSoJEF9U//
         iuKFyaQzDCPVWBsFAlkX8uzWDWNWvK0ovbU/qQjaS3fjyhHNJLEk1W++npzPtpC6
         rs3dvGJXJL1l54YnWztgIQkrONEDu0UoCOwJ2uRP4euQO+01AU2zg/Yy00GFzJpB
         RcX2VgzOjatBh/GFLJiWtdnRurjjTi0d9xD5VSkNk/qvS/5L+h0pt6y2Zfc3YV+7
         +6QxY45vgwn5M4xzqSC8SKumbergm2BXxt6J5fCjnqkcqdYtUDzGw4ffwlovlIy0
         SPaKJIUn4FjIlMnZDm3aQnjTVAnlXM6bWYKWLcn83MXFyK7MSrIa3Y7ByMoZp4xe
         Jvn+Wg0CgYEAuv5EDRqKFV7HLFQz8eOATauVqlB6lb46KcYTY4H3HnFqkQTMdPwF
         hciJBSnu153VYMT7UicYGTu7FD9knaF8qJDtXDEk+VBtt2fc0pu1dIZ6505tzNxV
         Q2/JUtRmUr9RMgu2ytEmHA1PiYP+/2RJ/l+7b/MzmkV8pGspJfvvLesCgYEAyEi1
         AeKRQYPTErGMmxBwtn1W2CLg1uWlRY2wrnHKtKUd0yW9+UzojdfKbYCIZ+pjvgzG
         tr7Ol94qwB9tk5KJActsgDohBk3ro4YzoYT42WReNH1bqUe6/8PgsXDrVz/9676X
         gZdbHoRbXfIkbDh3VQoPV4GskY8j5xywrzFhYyUCgYB+SOHkh5vhutSAV42NOruX
         uN2m3Bstrf7R33eQqGEgKjByJ+98wgdoxnnjBuLKs0k7xUyFuulHgVNi5T0qR7lM
         jjP/IyF5TpwKVRaJFaeCPqAaPplg1RywInqweclw8MwBJHAaoQ0/vK2OjZpVGIHw
         TO7lODYNZgg7cjOj93UcaQKBgQCgoPdS0LQwuBoDpxQelRvgsDuDUs3CbCGV2+J0
         tdyd7sMxwdZP6CenAwddtTUxKmHeXX7Nt9AXKt5cgZgvP9nT76NQX852sO2ok4w7
         IVs3dvC65kMqS9YlJKLDjM2ihzcN6Ci4jXxNyFdCzF370XmbYVsWknCluQhRZcgq
         ac8yZQKBgQCKG9TV5LQv1OfezNpBgKFkikEQndZSZXpNZqGfgsZ9BWJWbxq3s37/
         4OFdSYovw5tFY2Ma42kWO3cv3BYxoEsCeEMTHRRYfiM5IkYTY7gSO36yCq5MALDA
         IlzXBw2EuJIS3MjQbPR8AcXkV5l8TUrAIhgKOZUQum28uUn22MFheg==
         -----END RSA PRIVATE KEY-----
         

        BUNDLE_ID: "ru.msk.sovetdoma"
      flutter: 3.16.7
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up keychain to be used for codesigning using Codemagic CLI 'keychain' command
        script: |
          keychain initialize
      - name: Fetch signing files
        script: |
          app-store-connect fetch-signing-files $BUNDLE_ID --type IOS_APP_STORE --create --log-api-calls --verbose
      - name: Use system default keychain
        script: |
          keychain add-certificates
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Get Flutter packages
        script: |
          cd . && flutter packages pub get
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Flutter build ipa and automatic versioning
        script: |
          flutter build ipa --release --no-tree-shake-icons \
          --build-name=1.0.0 \
          --build-number=1 \
          --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      scripts:
        - name: HTTP notification
          script: |
            curl https://demoapi.flangapp.site/public/observe/notice?uid=5eb013f7-f0ab-3498-9803-e998837e0e5c