workflows:
  ios-workflow:
    name: Flangapp PRO iOS with publication
    max_build_duration: 30
    environment:
      vars:
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        APP_STORE_CONNECT_ISSUER_ID: 0f4b1570-ddfa-4aa9-b539-78a5df88ca47
        APP_STORE_CONNECT_KEY_IDENTIFIER: 97U6U53922
        APP_STORE_CONNECT_PRIVATE_KEY: |-
         -----BEGIN PRIVATE KEY-----
         MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgO4vnzck8OFtJokMx
         FRvqoqG0JLUUexSnL3/2gRAh0zCgCgYIKoZIzj0DAQehRANCAAQulsH+RV8QqiM6
         oTlrfH0hSH+HsLzjbpcYRc7Vba6Jlj7Hf7VwBRbOoaWErQ8y7KYQ1REH11jgOBLP
         fVlUshvt
         -----END PRIVATE KEY-----

        CERTIFICATE_PRIVATE_KEY: |-
         -----BEGIN RSA PRIVATE KEY-----
         MIIEpQIBAAKCAQEAwFiRtl7YxaFhJaZ1lF5folENKjyqrSN8HU+QPhAGEnJIzszJ
         X3ZJL3yn0YqvEEa2sh8CznKvLZe3886xHQ2ZAI6kZkSX/PfNeTYxSo77GKat8QD/
         4dw6czZpGwJcX4C3a22PHJ3H6ztuJ077+vTS5Q3QQTfcGXTu9RzaJYOP/WDfNTJi
         P5MHPXqTEJzRQBylrFNnTpr2mzeHf1fg5vjozLMngouxDlMcJjHjrk9Lp0C0/tlz
         Jv4TYDD3W4bMEmUqzGRI+VFVXFRjIdlJXYqfwLSvA2yUIPDSO1VhURfcni9nUU+e
         tMLgdX4vqvQcPkTPa4n99gIv13iKNwcC62hFvwIDAQABAoIBAA0yxqTd8z/0Z+ce
         efj5VNSdfSrFyOxif/S+7eXkUZZYcziFgtfjFPiGNDnDq2mRgJ3OVPH3mp+lRoEb
         ULnuoe4Q26UM1eUM1/OWTWGRWBeD8HGWIPjNlNEtDZ9F1TLUcUGU3foXtY0lodRe
         rhm1TPdcsEqZW6f/hxoYpbtnQK0hJxdNznPr7vpUfZnc/fZKyvGqXQ2Tb78zdSN+
         VxwS33Y3yi9ylZAoY67PPAp0D5mccNbWKl6JaCgFDSCkrHZIQbUCD/3gLWUwrQ6d
         RLfFGwr1LoQ+vAaVWwVNsxMDNM1tQBFKaQPofNcY2b+0SCw6MRDibkl1uZ4pNXQW
         v3AxvGkCgYEA5YgxYRZo0qE3k4yy6iI78+KlTv4divIK9BlAL2TbhsHuA7C9pHG7
         r9GvUI4Bo6D2ADBQLeH0dVuRMGqx54LQGn4IjBxJWhuJsSSJqmS2OPLo7WC0rsHK
         OpNjvlMw/IRiIjjxUKSiqsrj4ke4t3e18pCWA3L5HyqpNaYrgrjnUiMCgYEA1oak
         HSCalbZr4CDiV2rMwbOEnICCIIm9Jo62B47eDMKvtmSEuhUbuu9MgLMco6jt8mLF
         //Mh8UcaVQwq9c/s9Zei5XSstlnHUpBHECPu8K1VuFUOS6avo0ncGMoyQc7iE7V1
         khKLh/MIAlOTS7LlxfdjX+ef3CNXaE1x0IY7sbUCgYEArn4w+9vraGTDOVp3EWNh
         LHEatsiccOq8xQEFOIJ2GSYI6alNIlyMEIdZveWW/Wv6V/5ild721tj7sVELWjKq
         PdmeadV/Ng9FR/O87FqP5Q9VYFBqS4hrUsiFxUS9Mtr5N4cOfP4L48dGItnfZSqO
         mY6tXIXlOXpXFL/0x/YFdP0CgYEAmOD6s4c4otiNp/vHUWTa5m94Yc9y7J08Hu40
         6s31kEJt1h1sOPAyAtXmPxFlp3wLlmCtmek6lyeErHcvZl33EE4v2DV9n7X7Retr
         uSTicsIUBHkY5vCy2jsYjtIJXryAgGsgjiiJJyka3A2TOq8S8DGMsBvw4ICPGdWW
         9nOytsECgYEAg+SHm2CVX1vl9zIJ54fhj6KXMpBjxWPg+jFXfY9zzPnRWViWkilM
         Gys11MqmSlIAczUuNdZjE6bViMUeaAaH2Xst0UUgsppyPcyEQOF3kRe171ZUzudA
         6RaeTtYDUOHMwM6zngFCbWMK6WySINBDc5f/eRTYzHS/CLm7YDiOpgw=
         -----END RSA PRIVATE KEY-----
         

        BUNDLE_ID: "ru.msk.sovetdoma"
      flutter: 3.16.7
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up keychain to be used for codesigning using Codemagic CLI 'keychain' command
        script: |
          keychain initialize
      - name: Fetch signing files
        script: |
          app-store-connect fetch-signing-files $BUNDLE_ID --type IOS_APP_STORE --create --log-api-calls --verbose
      - name: Use system default keychain
        script: |
          keychain add-certificates
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Get Flutter packages
        script: |
          cd . && flutter packages pub get
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Flutter build ipa and automatic versioning
        script: |
          flutter build ipa --release --no-tree-shake-icons \
          --build-name=2.1.3 \
          --build-number=1 \
          --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
      scripts:
        - name: HTTP notification
          script: |
            curl https://demoapi.flangapp.site/public/observe/notice?uid=5d15e0ec-fb86-b3d3-df5a-1bf50698e1ab