
class Config {

  /// Generated by Flangapp PRO 27-11-2024 08:49
  /// App UID: 91869ba7-2642-17ef-4cb8-23b0e664687f
  /// Version: 1.0.2
  /// API server: https://demoapi.flangapp.site/

  /// *** Main settings *** ///
  static String apiUrl = "https://demoapi.flangapp.site/";
  static String appUid = "91869ba7-2642-17ef-4cb8-23b0e664687f";
  static String oneSignalPushId = "9662bd05-f396-4fe8-8f92-267c61ade3f6";

  /// *** Splashscreen settings *** ///
  // Background color (any HEX color)
  static String splashBackgroundColor = "#FFFFFF";
  // Text color (any HEX color)
  static String splashTextColor = "#ffffff";
  // Is image background
  static bool splashIsBackgroundImage = false;
  // Background image name
  static String splashBackgroundImage = "splash_screen.png";
  // Tagline
  static String splashTagline = "";
  // Delay display (seconds)
  static int splashDelay = 0;
  // Logo image name
  static String splashLogoImage = "splash_logo.png";
  // Display logo
  static bool splashIsDisplayLogo = false;

  /// *** Offline localization settings *** ///
  static String offlineErrorMessage = "No internet connection";
  static String offlineImage = "dino.png";

  /// *** Subscribe need settings *** ///
  static String subscribeErrorTitle = "App not available";
  static String subscribeErrorMessage = "This app may have been removed or your administrator may need to renew your subscription";
}